// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "59c8b059-79e4-4442-b880-bfbd0691cabb");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1602976738);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1602976797);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1602976768);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 2734);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1602976708);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{09f20b08-183c-4282-a3c9-d1264ce82bb2}");
user_pref("browser.newtabpage.enabled", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1602976746810");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1602978568810");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1602976712932");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1602980312932");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20201012085804");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1602976797");
user_pref("browser.slowStartup.averageTime", 1243);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage", "https://www.gentoo.org/");
user_pref("browser.startup.homepage_override.buildID", "20201012085804");
user_pref("browser.startup.homepage_override.mstone", "81.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1602976796);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1602976711590");
user_pref("distribution.iniFile.exists.appversion", "81.0.2");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("dom.push.userAgentID", "948f4ab1793746ceb65371648f37f33d");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20201012085804");
user_pref("extensions.lastAppVersion", "81.0.2");
user_pref("extensions.lastPlatformVersion", "81.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"3639c104-dca4-450d-8b95-7b0cbcef5c31\",\"formautofill@mozilla.org\":\"e87d8b96-e162-4c34-a8f8-c5c1a0995437\",\"screenshots@mozilla.org\":\"38d606c9-36f2-4012-b841-8f48ae86b372\",\"webcompat-reporter@mozilla.org\":\"94b56486-9b80-40a2-8095-5fcb67a4680d\",\"webcompat@mozilla.org\":\"b7541fd3-219e-45ea-b0e0-841f4d1a2ea6\",\"default-theme@mozilla.org\":\"c4f2c76a-e29b-4b45-95f7-649da15da1d9\",\"google@search.mozilla.org\":\"1cfae16d-45f6-462a-b4ac-fa31def9c24f\",\"amazondotcom@search.mozilla.org\":\"6baf0767-029d-4d9b-8d91-0da31798347a\",\"wikipedia@search.mozilla.org\":\"38ab2589-a9c8-4295-bc9b-e1d2fb51f75e\",\"bing@search.mozilla.org\":\"953636b9-93a5-4000-9b5c-a9912d3a01fe\",\"ddg@search.mozilla.org\":\"07f725f0-c3c8-45d0-a4bd-cc12ce2f75ff\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 21046);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "39b5eea1-c173-4f09-bb4b-fabedc95120a");
user_pref("security.sandbox.plugin.tempDirSuffix", "7f4c7f49-25bf-47d2-8551-f76f3d7eb5a7");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("signon.usage.hasEntry", false);
user_pref("toolkit.startup.last_success", 1602976795);
user_pref("toolkit.telemetry.cachedClientID", "7b3a0100-1633-4755-aa4c-12a2c68a1bb3");
user_pref("toolkit.telemetry.previousBuildID", "20201012085804");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
